spring.application.name=users-service

server.servlet.context-path=/users
server.port=9020

jwt.secretKey = asdfladf98a7df89aysf8d9yasiudfha9s87dfa89syudhfa98sdfyaisuhdfa98sfy

spring.datasource.url=jdbc:postgresql://${DB_SERVICE:users-db}:5432/${DB_NAME:linkedin_users}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:root}
spring.jpa.hibernate.ddl-auto=update

eureka.client.service-url.defaultZone= http://discovery-server:8761/eureka