spring.application.name=posts-service

server.servlet.context-path=/posts
server.port=9010

spring.datasource.url=jdbc:postgresql://${DB_SERVICE:posts-db}:5432/${DB_NAME:linkedin_posts}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:root}
spring.jpa.hibernate.ddl-auto=update

eureka.client.service-url.defaultZone= http://discovery-server:8761/eureka