apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-service
spec:
  selector:
    matchLabels:
      app: users-service
  template:
    metadata:
      labels:
        app: users-service
    spec:
      containers:
        - name: users-service
          image: sagar855/linkedin-app-users-service
          imagePullPolicy: Always
          resources:
            limits:
              memory: "400Mi"
              cpu: "200m"
            requests:
              memory: "200Mi"
              cpu: "100m"
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
            - name: DB_USER
              value: user
            - name: DB_PASSWORD
              value: password
            - name: DB_SERVICE
              value: users-db
            - name: DB_NAME
              value: userDB
          ports:
            - containerPort: 9020

---

apiVersion: v1
kind: Service
metadata:
  name: users-service
spec:
  selector:
    app: users-service
  ports:
    - port: 80
      targetPort: 9020


